#!/usr/bin/env python
import svtk
from svtk.util.misc import svtkGetDataRoot
SVTK_DATA_ROOT = svtkGetDataRoot()

# Created oriented text
text0Source = svtk.svtkTextSource()
text0Source.SetText("Text Source with Scalars (default)")
text0Mapper = svtk.svtkPolyDataMapper()
text0Mapper.SetInputConnection(text0Source.GetOutputPort())
text0Actor = svtk.svtkActor()
text0Actor.SetMapper(text0Mapper)
text0Actor.SetScale(.1,.1,.1)
text0Actor.AddPosition(0,2,0)
text1Source = svtk.svtkTextSource()
text1Source.SetText("Text Source with Scalars")
text1Source.SetForegroundColor(1,0,0)
text1Source.SetBackgroundColor(1,1,1)
text1Mapper = svtk.svtkPolyDataMapper()
text1Mapper.SetInputConnection(text1Source.GetOutputPort())
text1Actor = svtk.svtkActor()
text1Actor.SetMapper(text1Mapper)
text1Actor.SetScale(.1,.1,.1)
text2Source = svtk.svtkTextSource()
text2Source.SetText("Text Source without Scalars")
text2Source.BackingOff()
text2Mapper = svtk.svtkPolyDataMapper()
text2Mapper.SetInputConnection(text2Source.GetOutputPort())
text2Mapper.ScalarVisibilityOff()
text2Actor = svtk.svtkActor()
text2Actor.SetMapper(text2Mapper)
text2Actor.GetProperty().SetColor(1,1,0)
text2Actor.SetScale(.1,.1,.1)
text2Actor.AddPosition(0,-2,0)
text3Source = svtk.svtkVectorText()
text3Source.SetText("Vector Text")
text3Mapper = svtk.svtkPolyDataMapper()
text3Mapper.SetInputConnection(text3Source.GetOutputPort())
text3Mapper.ScalarVisibilityOff()
text3Actor = svtk.svtkActor()
text3Actor.SetMapper(text3Mapper)
text3Actor.GetProperty().SetColor(.1,1,0)
text3Actor.AddPosition(0,-4,0)
# create graphics stuff
ren1 = svtk.svtkRenderer()
renWin = svtk.svtkRenderWindow()
renWin.AddRenderer(ren1)
renWin.SetSize(350,100)
iren = svtk.svtkRenderWindowInteractor()
iren.SetRenderWindow(renWin)
ren1.AddActor(text0Actor)
ren1.AddActor(text1Actor)
ren1.AddActor(text2Actor)
ren1.AddActor(text3Actor)
ren1.ResetCamera()
ren1.GetActiveCamera().Zoom(3)
ren1.SetBackground(.1,.2,.4)
renWin.Render()
iren.Initialize()
# --- end of script --
