/*=========================================================================

  Program:   Visualization Toolkit
  Module:    svtkAbstractContextBufferId.h

  Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
  All rights reserved.
  See Copyright.txt or http://www.kitware.com/Copyright.htm for details.

     This software is distributed WITHOUT ANY WARRANTY; without even
     the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
     PURPOSE.  See the above copyright notice for more information.

=========================================================================*/

/**
 * @class   svtkAbstractContextBufferId
 * @brief   2D array of ids, used for picking.
 *
 *
 * An 2D array where each element is the id of an entity drawn at the given
 * pixel. The access is not specified in this class.
 * The effective/concrete subclass svtkContextBufferId stores the whole buffer
 * in RAM. The access to a value is fast and independent of the OpenGL.
 * However it requires to first fill the whole buffer by transferring the
 * buffer generated by OpenGL from the VRAM to the RAM. It is inefficient if
 * the context of the scene changes during interaction.
 *
 * The effective/concrete subclass svtkOpenGLContextBufferId keeps the buffer id
 * on the VRAM in a texture image. The access to a value is slower than a
 * simple read access to an array but it does not require a large transfer of
 * data from the VRAM to the RAM.
 *
 * @sa
 * svtkContextBufferId, svtkOpenGLContextBufferId
 */

#ifndef svtkAbstractContextBufferId_h
#define svtkAbstractContextBufferId_h

#include "svtkObject.h"
#include "svtkRenderingContext2DModule.h" // For export macro

class svtkRenderWindow;

class SVTKRENDERINGCONTEXT2D_EXPORT svtkAbstractContextBufferId : public svtkObject
{
public:
  svtkTypeMacro(svtkAbstractContextBufferId, svtkObject);
  void PrintSelf(ostream& os, svtkIndent indent) override;

  static svtkAbstractContextBufferId* New();

  //@{
  /**
   * Number of columns. Initial value is 0.
   */
  svtkGetMacro(Width, int);
  //@}

  //@{
  /**
   * Set the number of columns. Initial value is 0.
   */
  svtkSetMacro(Width, int);
  //@}

  //@{
  /**
   * Number of rows. Initial value is 0.
   */
  svtkGetMacro(Height, int);
  //@}

  //@{
  /**
   * Set the number of rows. Initial value is 0.
   */
  svtkSetMacro(Height, int);
  //@}

  //@{
  /**
   * Set/Get the OpenGL context owning the texture object resource.
   */
  virtual void SetContext(svtkRenderWindow* context) = 0;
  virtual svtkRenderWindow* GetContext() = 0;
  //@}

  /**
   * Returns if the context supports the required extensions.
   * \pre context_is_set: this->GetContext()!=0
   */
  virtual bool IsSupported() = 0;

  /**
   * Allocate the memory for at least Width*Height elements.
   * \pre positive_width: GetWidth()>0
   * \pre positive_height: GetHeight()>0
   */
  virtual void Allocate() = 0;

  /**
   * Tell if the buffer has been allocated.
   */
  virtual bool IsAllocated() const = 0;

  /**
   * Copy the contents of the current read buffer to the internal structure
   * starting at lower left corner of the framebuffer (srcXmin,srcYmin).
   * \pre is_allocated: this->IsAllocated()
   */
  virtual void SetValues(int srcXmin, int srcYmin) = 0;

  /**
   * Return item under abscissa x and ordinate y.
   * Abscissa go from left to right.
   * Ordinate go from bottom to top.
   * The return value is -1 if there is no item.
   * \pre is_allocated: IsAllocated()
   * \post valid_result: result>=-1
   */
  virtual svtkIdType GetPickedItem(int x, int y) = 0;

  /**
   * Release any graphics resources that are being consumed by this object.
   * Default implementation is empty.
   */
  virtual void ReleaseGraphicsResources();

protected:
  svtkAbstractContextBufferId();
  ~svtkAbstractContextBufferId() override;

  int Width;
  int Height;

private:
  svtkAbstractContextBufferId(const svtkAbstractContextBufferId&) = delete;
  void operator=(const svtkAbstractContextBufferId&) = delete;
};

#endif // #ifndef svtkAbstractContextBufferId_h
