package svtk;

/**
 * This interface provide all the methods needed for the management of svtkObject
 * in the Java world. They are used internally inside the generated Java code of
 * the SVTK objects to keep track of the reference count of the corresponding SVTK
 * C++ object and therefore allow to release memory when it became possible.
 *
 * Only the 3 following methods should be called by the user: - gc(boolean) : to
 * run the garbage collection - getAutoGarbageCollector() : to get the EDT
 * garbage collection scheduler - deleteAll() : to free any remaining SVTK
 * object.
 *
 * @author sebastien jourdain - sebastien.jourdain@kitware.com
 */
public interface svtkJavaMemoryManager {
  /**
   * Create or return an existing instance of the svtkObject that corresponds
   * to the pointer id svtkId.
   *
   * @param svtkId
   *            is used to uniquely identify a svtkObject inside the C++ layer.
   *
   * @return a java object that map its underlying C++ instance.
   */
  svtkObjectBase getJavaObject(Long svtkId);

  /**
   * Store the Java instance of a svtkObject inside a weak pointer map.
   *
   * @param id
   *            is used to uniquely identify a svtkObject inside the C++ layer.
   * @param obj
   *            is the Java instance that is stored inside a WeakPointer of
   *            the map.
   */
  void registerJavaObject(Long id, svtkObjectBase obj);

  /**
   * If found the Java object is removed from the map and we decrease the
   * reference count of the underneath C++ instance.
   *
   * @param id
   */
  void unRegisterJavaObject(Long id);

  /**
   * Execute the garbage collection in the Java + SVTK context to release Java
   * instance that are not used anymore which keep holding a C++ instance
   * around.
   *
   * @param debug
   *            allow to add extra information inside the return object such
   *            as the class name of the objects lefts as well as their
   *            numbers.
   *
   * @return an information object that provide useful information for
   *         statistic or debugging purpose.
   */
  svtkReferenceInformation gc(boolean debug);

  /**
   * @return an helper class that allow to trigger the garbage collector at a
   *         given frequency inside the EDT.
   */
  svtkJavaGarbageCollector getAutoGarbageCollector();

  /**
   * This method will clean up the Map of the Java objects and will release
   * any svtkObject that was held by a Java one. This will prevent you from
   * using any existing SVTK Java object.
   *
   * @return the size of the map that we cleared
   */
  int deleteAll();

  /**
   * @return the number of svtkObject that are currently used inside the Java
   *         world.
   */
  int getSize();

  /**
   * @return the svtkReferenceInformation object generated by the last gc() call
   */
  svtkReferenceInformation getLastReferenceInformation();
}
